app16/urls.py
from django.urls import path
from . import views
app_name='app16'

urlpatterns=[
    path('',views.index,name='index'),
    path('registration/',views.registration,name='registration'),
    path('login/',views.login,name='login'),
    path('home/<int:id>',views.home,name='home'),
    path('update/<int:id>',views.update,name='update'),
    path('delete/<int:id>',views.delete,name='delete'),
    path('changepassword/<int:id>',views.changepassword,name='changepassword'),
    path('logout/',views.logout,name='logout'),
    path('gallery/',views.gallery,name='gallery'),
    path('details/<int:id>',views.details,name='details'),
]

project16/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import static,staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app16.urls'))
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

app16/models.py
from django.db import models

# Create your models here.
class Register(models.Model):
    Name=models.CharField(max_length=10)
    Age=models.IntegerField()
    Place=models.CharField(max_length=10)
    Photo=models.ImageField(upload_to='media/',null=True,blank=True)
    Email=models.EmailField()
    Password=models.CharField(max_length=10)

class Gallery(models.Model): 
   Brand=models.CharField(max_length=10)
   Name=models.CharField(max_length=10)
   Photo=models.ImageField(upload_to='media/',null=True,blank=True)
   Price=models.IntegerField()

app16/forms.py
from django import forms
from . models import Register
class RegisterForm(forms.ModelForm): 
    Password=forms.CharField(widget=forms.PasswordInput,max_length=8,min_length=2)
    ConfirmPassword=forms.CharField(widget=forms.PasswordInput,max_length=8,min_length=2)
    class Meta():
        model=Register                                         
        fields='__all__'

class LoginForm(forms.ModelForm):
    Password=forms.CharField(widget=forms.PasswordInput,max_length=8,min_length=2)
    class Meta():
        model=Register
        fields=('Email','Password')

class UpdateForm(forms.ModelForm):
    class Meta():
        model=Register
        fields=('Name','Age','Place','Email')
        
class ChangepasswordForm(forms.Form):
    OldPassword=forms.CharField(widget=forms.PasswordInput,max_length=8,min_length=2)
    NewPassword=forms.CharField(widget=forms.PasswordInput,max_length=8,min_length=2)
    ConfirmPassword=forms.CharField(widget=forms.PasswordInput,max_length=8,min_length=2)

app16/views.py
from django.shortcuts import render,redirect
from django.contrib import messages
from.forms import RegisterForm, LoginForm, UpdateForm,ChangepasswordForm
from.models import Register,Gallery
from django.contrib.auth import logout as logouts

from django.conf import settings
from django.core.mail import send_mail


# Create your views here.
def index(request):
    return render(request,'index.html')
def registration(request):
    if request.method=='POST':
        form=RegisterForm(request.POST)
        if form.is_valid():
            name=form.cleaned_data['Name']
            age=form.cleaned_data['Age']
            photo=form.cleaned_data['Photo']
            place=form.cleaned_data['Place']
            email=form.cleaned_data['Email']
            password=form.cleaned_data['Password']
            confirmpassword=form.cleaned_data['ConfirmPassword']

            user=Register.objects.filter(Email=email).exists()
            if user:
                messages.warning(request,'Email Alredy exist')
                return redirect('/login')
            elif password!=confirmpassword:
                messages.warning(request,'Password Mismatch')
            else:
                tab=Register(Name=name,Age=age,Place=place,Email=email,Photo=photo,Password=password)
                tab.save()


                subject = 'welcome to abc '
                message = f'Hi {name}, thank you for registering in geeksforgeeks.'
                email_from = settings.EMAIL_HOST_USER
                recipient_list = [email, ]
                send_mail( subject, message, email_from, recipient_list )




                messages.success(request,'DATA SAVED')
                return redirect('/login')
    else:
        form=RegisterForm() 
    return render(request,'registration.html',{'form':form})
    
def login(request):
    if request.method=='POST':
        form=LoginForm(request.POST)
        if form.is_valid():
            email=form.cleaned_data['Email']
            password=form.cleaned_data['Password']
            try:
                user=Register.objects.get(Email=email)
                if not user:
                    messages.warning(request,'Email does not exist')
                    return redirect('/login')
                elif password!=user.Password:
                    messages.warning(request,'Password Incorrect')
                    return redirect('/login')
                else:
                    messages.success(request,'Success')
                    return redirect('/home/%s' % user.id)
            except:
                messages.warning(request,'Email or Password incorrect')
                return redirect('/login')
    else:
        form=LoginForm()
    return render(request,'login.html',{'form':form})
def home(request,id):
        user=Register.objects.get(id=id)
        return render(request,'home.html',{'user':user})

def update(request,id):
    user=Register.objects.get(id=id)
    if request.method=='POST':
        form=UpdateForm(request.POST or None,instance=user)
        if form.is_valid():
            form.save()
            messages.success(request,'Success')
            return redirect('/home/%s' % user.id)
    else:
        form=UpdateForm(instance=user)
    return render(request,'update.html',{'user':user,'form':form})

def delete(request):
    user=Register.objects.get(id=id)
    user.delete()
    messages.success(request,'SUCCESS')
    return redirect('/')

def logout(request):
    logouts(request)
    messages.success(request,'SUCCESS')
    return redirect('/')


def changepassword(request,id):
    user=Register.objects.get(id=id)
    if request.method=='POST':
        form=ChangepasswordForm(request.POST or None)
        if form.is_valid():
            oldpassword=form.cleaned_data['OldPassword']
            newpassword=form.cleaned_data['NewPassword']
            confirmpassword=form.cleaned_data['ConfirmPassword']

            if oldpassword!= user.Password:
                messages.warning(request,"incorrect")
                return redirect('/changepassword/%s' % user.id)
            elif oldpassword==newpassword: 
                messages.warning(request, "password similar")
                return redirect('/changepassword/%s' % user.id)
            elif newpassword!=confirmpassword:
                messages.warning(request,"password new")
                return redirect('/'% user.id)
            else:
                user.Password=newpassword
                user.save()
                messages.success(request,"change success")
    else:
        form=ChangepasswordForm()
        return render(request,'changepassword.html',{'user':user, 'form':form})

def logout(request):
    logouts(request)
    messages.success(request,"logged out")
    return redirect('/')

def gallery(request):
    images=Gallery.objects.all()
    return render(request,'gallery.html',{'images':images})

def details(request, id): 
    images=Gallery.objects.get(id=id)
    return render(request,'details.html',{'images':images}) 

app16/templates/changepassword.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% for m in messages %}
    {{m}}
    {% endfor %}
    <form action="" method="post">
        {% csrf_token %}
        <table>
            <tr>
                {{form.as_table}}
            </tr>
        </table>
        <input type="submit" value="changepassword">
    </form>
</body>
</html>

app16/templates/details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {{images.id}}
    {{images.Brand}}
    {{images.Name}}
    {{images.Price}}
    
    <img style="width:200px;height:100px;" src="{{images.Photo.url}}">

    
    </body>
</html>

app16/templates/gallery.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
   

  <table>
    <tr>
        <th>Name</th>
        <th>Photo</th>
        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
    </tr>
    {% for img in images %}
    <tr>
        <td>{{img.Name}}</td>
        <td><a href="{% url 'app16:details' img.id %}"><img src="{{ img.Photo.url }}" height="100px" width="200px"></a></td>
        
    </tr>
    {% endfor %}</td>
    </tr>
</table>

app16/templates/home.html
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% for m in messages %}
    {{m}}
    {% endfor %}
    {{user.id}}
    {{user.name}}
    <a href="{% url 'app16:update' user.id %}">Update</a>
    <a href="{% url 'app16:delete' user.id %}">Delete</a>
    <a href="{% url 'app16:changepassword' user.id %}">changepassword</a>
    <a href="{% url 'app16:logout' %}">Logout</a>

   
</body>
</html>

app16/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% for m in messages %}
    {{m}}
    {% endfor %}
    <form action="" method="post" >
    <a href="{% url 'app16:login' %}">Login</a>
    <a href="{% url 'app16:gallery' %}">Gallery</a>
    </form>
</body>
</html>

app16/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% for m in messages %}
    {{m}}
    {% endfor %}
    <form action="" method="post" >
        {% csrf_token %}
        <table>
            <tr>{{form.as_table}} </tr>
        </table>            
        <input type="submit" value="Login">
    </form>
    <a href="{% url 'app16:registration' %}">Create account</a>
</body>
</html>

app16/templates/registration.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% for m in messages %}
    {{m}}
    {% endfor %}
    <form action="" method="post">
        {% csrf_token %}
        <table>
            <tr>{{form.as_table}}</tr>
        </table>
        <input type="submit" value="submit">
       
    </form>
      
</body>
</html>

app16/templates/update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% for m in messages %}
    {{m}}
    {% endfor %}
    
    <form action="" method="post">
        {% csrf_token %}
        <table>
            <tr>{{form.as_table}}</tr>
        </table>
        <input type="submit" value="update">
       
    </form>
      
</body>
</html>